#!/bin/bash
command="$1";
client_id=$(awk "NR==1{print;exit}" /home/hadoop/TESAPI/TESTSCRIPT/Box/cliID.box)
client_secret=$(awk "NR==1{print;exit}" /home/hadoop/TESAPI/TESTSCRIPT/Box/cliSECRET.box)
#client_id="qs9oulna0fakkkxjorbvc0bpv8113423"
#client_secret="tAtjbtmbkIp5n6vQsWBeX1SyOoYVq66M"

while read line
do
	refresh_token="$line"
done < /home/hadoop/TESAPI/TESTSCRIPT/Box/refreshtoken.box1
#echo "refresh token = ${refresh_token}"

curl "https://app.box.com/api/oauth2/token"  -d "grant_type=refresh_token&refresh_token=${refresh_token}&client_id=${client_id}&client_secret=${client_secret}"  -X "POST" -s | jq '.access_token' | cut -d'"' -f2 > /home/hadoop/TESAPI/TESTSCRIPT/Box/token.box1
curl "https://app.box.com/api/oauth2/token"  -d "grant_type=refresh_token&refresh_token=${refresh_token}&client_id=${client_id}&client_secret=${client_secret}"  -X "POST" -s | jq '.refresh_token' | cut -d'"' -f2 > /home/hadoop/TESAPI/TESTSCRIPT/Box/refreshtoken.box1




